name: 'brt_gps_project'
version: '1.0.0'
config-version: 2
profile: 'brt_gps_project'
model-paths: ["dbt_models"]
seed-paths: ["data"]
log-path: logs
target-path: target
clean-targets:
  - target
  - logs

