version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brt_db
    ports:
      - "5432:5432"

  prefect:
    image: prefecthq/prefect:0.15.9
    environment:
      PREFECT__BACKEND: "server"
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: ["prefect", "server", "start"]

  dbt:
    image: fishtownanalytics/dbt
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    volumes:
      - .:/app
    command: ["dbt", "run"]
